# Generated by Django 4.0.2 on 2022-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='content',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='confirm_password',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='users',
            name='user_location',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='userid',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
