# Generated by Django 4.0.3 on 2022-03-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
    ]
