# Generated by Django 4.0.3 on 2022-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='braceletsettings',
            fields=[
                ('userid', models.IntegerField(default=True, primary_key=True, serialize=False)),
                ('how_to_use', models.CharField(default=True, max_length=300)),
                ('edit_name', models.CharField(default=True, max_length=40)),
            ],
        ),
    ]
