# Generated by Django 4.0.2 on 2022-03-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='preveleges',
            field=models.BooleanField(default=True),
        ),
    ]
