# Generated by Django 4.0.2 on 2022-03-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_admin_preveleges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='preveleges',
        ),
        migrations.AddField(
            model_name='admin',
            name='superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
