# Generated by Django 4.0.2 on 2022-03-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_remove_admin_preveleges_admin_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
