# Generated by Django 4.0.3 on 2022-03-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_admin_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='superadmin',
        ),
    ]
