# Generated by Django 4.0.3 on 2022-03-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_admin_profpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
